set -euo pipefail
test "$SUITE" = transport-full
test "$BASE_SHA" = 1e254336b194c48f97342d8dd9024b8e59c14be2
test "$(git rev-parse HEAD^{tree})" = "$EXPECTED_TREE"
test ! -e src/gateway/worker-environments/transport-source-authority.test.ts
pnpm test src/gateway/worker-environments/node-worker-repository-authority.test.ts src/gateway/worker-environments/node-worker-tunnel-authority.test.ts src/gateway/worker-environments/node-worker-workspace-actions.test.ts src/gateway/worker-environments/node-worker-workspace-fallback.test.ts src/gateway/worker-environments/node-worker-workspace-publication.test.ts src/gateway/worker-environments/node-worker-tunnel.test.ts src/gateway/worker-environments/environment-access.test.ts src/gateway/worker-environments/ssh.test.ts src/gateway/worker-environments/tunnel.test.ts src/gateway/worker-environments/workspace-sync-tunnel.test.ts src/gateway/worker-environments/repository-workspace-startup.test.ts src/gateway/worker-environments/node-workspace-transfer-command.test.ts src/gateway/worker-environments/node-workspace-transfer-service.test.ts src/gateway/worker-environments/node-workspace-transfer-pack.test.ts src/gateway/worker-environments/node-workspace-transfer-retention.test.ts src/gateway/worker-environments/node-workspace-transfer-revocation.test.ts src/gateway/worker-environments/node-workspace-transfer-encoding.test.ts src/gateway/worker-environments/node-workspace-transfer-credential.test.ts src/gateway/worker-environments/placement-dispatch.test.ts src/gateway/worker-environments/placement-dispatch-device.test.ts src/gateway/worker-environments/placement-dispatch-prepared.test.ts
pnpm check:line-cap-ratchet --base "$BASE_SHA"
pnpm check:max-lines-ratchet --base "$BASE_SHA"
pnpm tsgo:core
node scripts/run-tsgo-core-test-shards.mjs --changed-paths-json '["src/gateway/worker-environments/placement-dispatch-device.test.ts","src/gateway/worker-environments/environment-access.test.ts","src/gateway/worker-environments/environment-access.ts","src/gateway/worker-environments/node-worker-repository-authority.test.ts","src/gateway/worker-environments/node-worker-repository-preparation.ts","src/gateway/worker-environments/node-worker-tunnel-authority.test.ts","src/gateway/worker-environments/node-worker-tunnel.ts","src/gateway/worker-environments/node-worker-workspace-actions.test.ts","src/gateway/worker-environments/node-worker-workspace-actions.ts","src/gateway/worker-environments/node-worker-workspace-fallback.test.ts","src/gateway/worker-environments/node-worker-workspace-fallback.ts","src/gateway/worker-environments/node-workspace-transfer-command.test.ts","src/gateway/worker-environments/node-workspace-transfer-command.ts","src/gateway/worker-environments/node-workspace-transfer-encoding.test.ts","src/gateway/worker-environments/node-workspace-transfer-owner.ts","src/gateway/worker-environments/node-workspace-transfer-retention.test.ts","src/gateway/worker-environments/node-workspace-transfer-service.test.ts","src/gateway/worker-environments/node-workspace-transfer-service.ts","src/gateway/worker-environments/placement-dispatch-failure.ts","src/gateway/worker-environments/placement-dispatch-startup.ts","src/gateway/worker-environments/repository-workspace-startup.test.ts","src/gateway/worker-environments/repository-workspace-startup.ts","src/gateway/worker-environments/session-workspace.ts","src/gateway/worker-environments/tunnel-contract.ts","src/gateway/worker-environments/tunnel.test.ts","src/gateway/worker-environments/tunnel.ts","src/gateway/worker-environments/workspace-sync-transport.ts","src/gateway/worker-environments/workspace-sync-tunnel.test.ts","src/gateway/worker-environments/workspace-sync.ts"]'
git diff --name-only --diff-filter=ACMR -z "$BASE_SHA" HEAD -- '*.ts' '*.mts' '*.js' '*.mjs' > "$RUNNER_TEMP/lint-files"
mapfile -d '' -t lint < "$RUNNER_TEMP/lint-files"
test "${#lint[@]}" -gt 0
node scripts/run-oxlint.mjs --tsconfig config/tsconfig/oxlint.core.json "${lint[@]}"
git diff --name-only --diff-filter=ACMR -z "$BASE_SHA" HEAD > "$RUNNER_TEMP/changed-files"
mapfile -d '' -t changed < "$RUNNER_TEMP/changed-files"
test "${#changed[@]}" -gt 0
./node_modules/.bin/oxfmt --check "${changed[@]}"
git diff --check "$BASE_SHA" HEAD
